# KhushiDL - Heart Disease (EDA)

In [18]:
# importing the necessary modules
import pandas as pd

### Reading the Data

In [19]:
# Viewing adjustments
pd.set_option('display.max_rows', None)  # Shows all rows
pd.set_option('display.max_columns', None)  # Shows all columns
pd.set_option('display.width', 1000)  # Prevents wrapping to new lines

In [20]:
swiss_data = pd.read_csv('data/processed.switzerland.data', header=None)
cleve_data = pd.read_csv('data/processed.cleveland.data')
hungarian_data = pd.read_csv('data/processed.hungarian.data')
va_data = pd.read_csv('data/processed.va.data')

### Swiss Data 🇨🇭

In [21]:
swiss_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       123 non-null    int64
 1   1       123 non-null    int64
 2   2       123 non-null    int64
 3   3       123 non-null    str
 4   4       123 non-null    int64
 5   5       123 non-null    str
 6   6       123 non-null    str
 7   7       123 non-null    str
 8   8       123 non-null    str
 9   9       123 non-null    str
 10  10      123 non-null    str
 11  11      123 non-null    str
 12  12      123 non-null    str
 13  13      123 non-null    int64
dtypes: int64(5), str(9)
memory usage: 13.6 KB

In [25]:
swiss_data.head()

   0   1   2    3   4  5  6    7  8    9  10 11 12  13
0  32   1   1   95   0  ?  0  127  0   .7  1  ?  ?   1
1  34   1   4  115   0  ?  ?  154  0   .2  1  ?  ?   1
2  35   1   4    ?   0  ?  0  130  1    ?  ?  ?  7   3
3  36   1   4  110   0  ?  0  125  1    1  2  ?  6   1
4  38   0   4  105   0  ?  0  166  0  2.8  1  ?  ?   2

In [24]:
swiss_data.describe().T

    count       mean       std   min   25%   50%   75%   max
0   123.0  55.317073  9.032108  32.0  51.0  56.0  61.5  74.0
1   123.0   0.918699  0.274414   0.0   1.0   1.0   1.0   1.0
2   123.0   3.699187  0.688726   1.0   4.0   4.0   4.0   4.0
4   123.0   0.000000  0.000000   0.0   0.0   0.0   0.0   0.0
13  123.0   1.804878  1.013503   0.0   1.0   2.0   3.0   4.0